import type { Metadata } from "next";
// ❌ خطوط زیر که فونت‌های گوگل را لود می‌کنند، حذف یا کامنت شوند.
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// ❌ تعریف‌های زیر که فونت‌های گوگل را تنظیم می‌کنند، حذف یا کامنت شوند.
/*
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
*/

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className="app-font-iranian-sans antialiased">{children}</body>
    </html>
  );
}
